### PR TITLE
bumps tensorflow to >=1.15.1,<2.0.0

### PR DESCRIPTION
**Pull request by lsh-0**
regarding the security issue [GHSA-977j-xj7q-2jr9
](https://github.com/elifesciences/sciencebeam-trainer-delft/network/alert/requirements.cpu.txt/tensorflow/open)

### CODE REVIEW

**Comment by lsh-0** [comment]
> We are additionally releasing TensorFlow 1.15.1 and 2.0.1 with this vulnerability patched.

I guess they haven't yet:

```
[2020-01-30T06:39:34.696Z] Collecting tensorflow<2.0.0,>=1.15.1 (from -r /opt/sciencebeam-trainer-delft/requirements.cpu.txt (line 1))
[2020-01-30T06:39:34.696Z]   Could not find a version that satisfies the requirement tensorflow<2.0.0,>=1.15.1 (from -r /opt/sciencebeam-trainer-delft/requirements.cpu.txt (line 1)) (from versions: 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
[2020-01-30T06:39:34.696Z] No matching distribution found for tensorflow<2.0.0,>=1.15.1 (from -r /opt/sciencebeam-trainer-delft/requirements.cpu.txt (line 1))
```

**Comment by lsh-0** [comment]
hrm, no, they're [definitely](https://github.com/tensorflow/tensorflow/releases/) [there](https://pypi.org/project/tensorflow/#history).

**Comment by lsh-0** [comment]
@de-code could you take a look at this please? it's not the version of pip being used. It might be related to this [issue](https://github.com/tensorflow/tensorflow/issues/36347).

**Comment by de-code** [comment]
I added pip to the `requirements.build.txt` which I already had in the project but wasn't used by the Dockerfile. I guess it was either `setuptools` or `wheel` that fixed it.
(Adding it to `requirements.build.txt` also has the added advantage that it works with a virtual environment without using docker)

**Comment by lsh-0** [comment]
thanks @de-code , it's appreciated

**Pull request merged**
